# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/aburgh/Projects/iPhone/usbmuxd/CMakeFiles/CMakeCCompiler.cmake\
/Users/aburgh/Projects/iPhone/usbmuxd/CMakeFiles/CMakeCXXCompiler.cmake\
/Users/aburgh/Projects/iPhone/usbmuxd/CMakeFiles/CMakeSystem.cmake\
/Users/aburgh/Projects/iPhone/usbmuxd/CMakeLists.txt\
/Users/aburgh/Projects/iPhone/usbmuxd/Modules/cmake_uninstall.cmake.in\
/Users/aburgh/Projects/iPhone/usbmuxd/libusbmuxd.pc.in\
/usr/local/share/cmake-2.6/Modules/CMakeCInformation.cmake\
/usr/local/share/cmake-2.6/Modules/CMakeCXXInformation.cmake\
/usr/local/share/cmake-2.6/Modules/CMakeCommonLanguageInclude.cmake\
/usr/local/share/cmake-2.6/Modules/CMakeGenericSystem.cmake\
/usr/local/share/cmake-2.6/Modules/CMakeSystemSpecificInformation.cmake\
/usr/local/share/cmake-2.6/Modules/Platform/Darwin.cmake\
/usr/local/share/cmake-2.6/Modules/Platform/UnixPaths.cmake\
/usr/local/share/cmake-2.6/Modules/Platform/gcc.cmake
	/usr/local/bin/cmake -H/Users/aburgh/Projects/iPhone/usbmuxd -B/Users/aburgh/Projects/iPhone/usbmuxd
